ignoredBuiltDependencies:
  - better-sqlite3
onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

packages:
  - 'app'
  - 'components'
  - 'lib'